module VerifyExamples.Direction.FromCoord0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Direction exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#fromCoord: \n\n    { x = 1, y = 1 }\n        |> fromCoord\n    --> Nothing" <|
        \() ->
            Expect.equal
                (
                { x = 1, y = 1 }
                    |> fromCoord
                )
                (
                Nothing
                )