module VerifyExamples.Direction.FromCoord4 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Direction exposing (..)







spec4 : Test.Test
spec4 =
    Test.test "#fromCoord: \n\n    { x = 0, y = 1 }\n        |> fromCoord\n    --> Just Down" <|
        \() ->
            Expect.equal
                (
                { x = 0, y = 1 }
                    |> fromCoord
                )
                (
                Just Down
                )