module VerifyExamples.Direction.FromCoord3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Direction exposing (..)







spec3 : Test.Test
spec3 =
    Test.test "#fromCoord: \n\n    { x = 0, y = -1 }\n        |> fromCoord\n    --> Just Up" <|
        \() ->
            Expect.equal
                (
                { x = 0, y = -1 }
                    |> fromCoord
                )
                (
                Just Up
                )