module VerifyExamples.Direction.Mirror1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Direction exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#mirror: \n\n    Up\n    |> mirror\n    --> Down" <|
        \() ->
            Expect.equal
                (
                Up
                |> mirror
                )
                (
                Down
                )