module VerifyExamples.Direction.RotateRightwise0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Direction exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#rotateRightwise: \n\n    Up\n        |> rotateRightwise\n    --> Right" <|
        \() ->
            Expect.equal
                (
                Up
                    |> rotateRightwise
                )
                (
                Right
                )