module VerifyExamples.Direction.RotateLeftwise0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Direction exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#rotateLeftwise: \n\n    Up\n        |> rotateLeftwise\n    --> Left" <|
        \() ->
            Expect.equal
                (
                Up
                    |> rotateLeftwise
                )
                (
                Left
                )