module VerifyExamples.Direction.ToCoord0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Direction exposing (..)



list : List Direction
list =
    asList
    |> (\(head,tail) -> head :: tail)



spec0 : Test.Test
spec0 =
    Test.test "#toCoord: \n\n    Right\n        |> toCoord\n    --> {x = 1, y = 0}" <|
        \() ->
            Expect.equal
                (
                Right
                    |> toCoord
                )
                (
                {x = 1, y = 0}
                )