module VerifyExamples.Direction.ToCoord1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Direction exposing (..)



list : List Direction
list =
    asList
    |> (\(head,tail) -> head :: tail)



spec1 : Test.Test
spec1 =
    Test.test "#toCoord: \n\n    list\n        |> List.map toCoord\n        |> List.filterMap fromCoord\n    --> list" <|
        \() ->
            Expect.equal
                (
                list
                    |> List.map toCoord
                    |> List.filterMap fromCoord
                )
                (
                list
                )