module VerifyExamples.Grid.Init0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Grid exposing (..)



dimensions : { columns:Int , rows:Int }
dimensions =
    { columns=42
    , rows=3
    }



spec0 : Test.Test
spec0 =
    Test.test "#init: \n\n    init (always <| Just ()) dimensions |> emptyPositions\n    --> []" <|
        \() ->
            Expect.equal
                (
                init (always <| Just ()) dimensions |> emptyPositions
                )
                (
                []
                )