module VerifyExamples.Grid.ToList0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Grid exposing (..)



grid : Grid (Maybe Int)
grid =
    empty dimensions
dimensions : { columns:Int , rows:Int }
dimensions =
    { columns=2
    , rows=2
    }



spec0 : Test.Test
spec0 =
    Test.test "#toList: \n\n    grid |> insert (1,1) 42 |> toList\n    --> [( (0,0), Nothing ),((1,0), Nothing ),((0,1), Nothing ),( (1,1), Just 42 )]" <|
        \() ->
            Expect.equal
                (
                grid |> insert (1,1) 42 |> toList
                )
                (
                [( (0,0), Nothing ),((1,0), Nothing ),((0,1), Nothing ),( (1,1), Just 42 )]
                )