module VerifyExamples.Position.Add0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Position exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#add: \n\n    (2,3)\n    |> add { x = 1, y = 0}\n    --> (3,3)" <|
        \() ->
            Expect.equal
                (
                (2,3)
                |> add { x = 1, y = 0}
                )
                (
                (3,3)
                )