module VerifyExamples.Position.CoordTo0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Position exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#coordTo: \n\n    (1,1)\n    |> coordTo (1,2)\n    --> { x = 0, y = 1 }" <|
        \() ->
            Expect.equal
                (
                (1,1)
                |> coordTo (1,2)
                )
                (
                { x = 0, y = 1 }
                )